# Generated by Django 4.1 on 2022-08-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auth_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('code', models.CharField(max_length=4)),
                ('toverify', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='events_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('selection', models.CharField(max_length=2)),
                ('time', models.CharField(max_length=20)),
                ('week', models.CharField(blank=True, max_length=20)),
                ('song', models.CharField(max_length=4)),
                ('currentyear', models.BooleanField(default=False)),
            ],
        ),
    ]
