# Generated by Django 4.1 on 2022-08-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clock_hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
