# Generated by Django 4.1 on 2022-08-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='events_backups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=11)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
