# Generated by Django 4.1 on 2022-08-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0002_clock_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSongsBackups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=11)),
                ('song_file', models.FileField(upload_to='songs/')),
                ('creation_date', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='clock_hour',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
