# Generated by Django 4.1 on 2022-08-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0002_events_backups'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_backups',
            name='creationdate',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
