# Generated by Django 4.1 on 2022-08-21 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0003_eventsongsbackups_clock_hour_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSongsFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='file_name_create_retrieve', to='paginaweb.eventsongsbackups')),
                ('song_file', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='song_file_create_retrieve', to='paginaweb.eventsongsbackups')),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='title_create_retrieve', to='paginaweb.eventsongsbackups')),
            ],
        ),
    ]
