# Generated by Django 4.1 on 2022-08-21 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paginaweb', '0005_authcodeverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcodeverification',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_email', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authcodeverification',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_username', to=settings.AUTH_USER_MODEL),
        ),
    ]
