# Generated by Django 4.1 on 2022-08-21 22:54

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0006_alter_authcodeverification_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsongsbackups',
            name='song_file',
            field=models.FileField(upload_to=django.core.files.storage.FileSystemStorage(location='/home/campanario/campanario/campanario_chaleco/campanario/media/songs/')),
        ),
    ]
