# Generated by Django 4.1 on 2022-08-21 23:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0007_alter_eventsongsbackups_song_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsongsbackups',
            name='creation_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventsongsbackups',
            name='song_file',
            field=models.FileField(upload_to=django.core.files.storage.FileSystemStorage(location='/backups/')),
        ),
    ]
