# Generated by Django 4.1 on 2022-08-21 23:23

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0008_alter_eventsongsbackups_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsongsfiles',
            name='song_file',
            field=models.FileField(upload_to=django.core.files.storage.FileSystemStorage(location='/backups/')),
        ),
    ]
