# Generated by Django 4.1 on 2022-08-29 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0009_alter_eventsongsfiles_song_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='clock_hour',
        ),
        migrations.AlterField(
            model_name='eventsongsfiles',
            name='file_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='filename_create_retrieve', to='paginaweb.eventsongsbackups'),
        ),
    ]
